name: Build and release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and release mobile app with fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use ruby version 2.7.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
          bundler-cache: true
      - name: Install project dependencies
        run: yarn install && bundle install
      - name: Build and release
        run: bundle exec fastlane --version
        env:
          # GitHub token to pull private repo
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          # The password to decrypt certificates, previously configured with match
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          # App Store Connect API key
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
