name: Build and release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and release mobile app with fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and release
        run: fastlane --version
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_READONLY: true
